version: '2.3'
services:
  els-kibana:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '9200:9200' # elastic
      - '5601:5601' # kibana
    volumes:
      - ..:/app
